export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const ADD_INGREDIENT_BUN = 'ADD_INGREDIENT_BUN';
export const MOVE_INGREDIENT = 'MOVE_INGREDIENT';
export const DELETE_INGREDIENT = 'DELETE_INGREDIENT';